// Builds the browser pieces the relay serves (the phone page, the dashboard and the JS client's
// <script> build) and writes them into packages/relay/src/generated/assets.ts, so both `bun run`
// and the compiled relay binary carry them.
//
//   bun scripts/build-assets.ts

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..");

async function bundle(entry: string, format: "iife" | "esm" = "iife"): Promise<string> {
  const out = await Bun.build({ entrypoints: [join(root, entry)], target: "browser", format, minify: true });
  if (!out.success) {
    for (const log of out.logs) console.error(log);
    throw new Error(`build failed: ${entry}`);
  }
  return await out.outputs[0].text();
}

function page(dir: string, js: string): string {
  const html = readFileSync(join(root, dir, "index.html"), "utf8");
  const css = readFileSync(join(root, dir, "style.css"), "utf8");
  // A literal "</script" inside the bundle would end the inline script early.
  const safeJs = js.replace(/<\/script/gi, "<\\/script");
  return html.replace("/*STYLE*/", () => css).replace("/*SCRIPT*/", () => safeJs);
}

export async function buildAssets(): Promise<void> {
  const [phone, dashboard, client] = await Promise.all([
    bundle("packages/phone/src/main.ts"),
    bundle("packages/dashboard/src/main.ts"),
    bundle("packages/client-js/src/global.ts"),
  ]);
  const outDir = join(root, "packages/relay/src/generated");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    join(outDir, "assets.ts"),
    [
      "// Generated by scripts/build-assets.ts. Do not edit.",
      `export const PHONE_HTML = ${JSON.stringify(page("packages/phone/src", phone))};`,
      `export const DASHBOARD_HTML = ${JSON.stringify(page("packages/dashboard/src", dashboard))};`,
      `export const CLIENT_JS = ${JSON.stringify(client)};`,
      "",
    ].join("\n"),
  );
  console.log(`assets: phone ${(phone.length / 1024).toFixed(1)} KB, dashboard ${(dashboard.length / 1024).toFixed(1)} KB, client ${(client.length / 1024).toFixed(1)} KB`);
}

if (import.meta.main) await buildAssets();
